name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - "Infra/**"
      - "!Infra/envs/*.tfvars"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-region: ${{secrets.AWS_REGION}}
          role-to-assume: ${{secrets.AWS_IAM_ARN}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init -reconfigure

      - name: Terraform Plan
        run: |
          set +e
          terraform plan \
            -var-file=envs/dev.tfvars \
            -out=tfplan \
          EXIT_CODE=$?
          if [ $EXIT_CODE -eq 1 ]; then
            echo "Terraform plan failed with error"
            exit 1
          fi
          exit 0

      - name: Terraform Apply
        run: terraform apply -var-file="envs/dev.tfvars" --auto-approve tfplan

      - name: Terraform Output
        run: terraform output
        continue-on-error: true
