name: Terraform Destroy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: Terraform Destroy (${{ github.event.inputs.environment }})
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-region: ${{secrets.AWS_REGION}}
          role-to-assume: ${{secrets.AWS_IAM_ARN}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init
        run: |
          terraform init -reconfigure

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Destory
        run: terraform destroy -var-file="envs/dev.tfvars" --auto-approve

      - name: Destroy summary
        run: |
          echo "## Destroy Complete" >> $GITHUB_STEP_SUMMARY
          echo "| Field | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|-------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Environment | $ENV |" >> $GITHUB_STEP_SUMMARY
          echo "| Status | All resources destroyed |" >> $GITHUB_STEP_SUMMARY
          echo "| Triggered by | ${{ github.actor }} |" >> $GITHUB_STEP_SUMMARY
