name: Terraform Plan

on:
  pull_request:
    branches:
      - main
    paths:
      - "Infra/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-region: ${{secrets.AWS_REGION}}
          role-to-assume: ${{secrets.AWS_IAM_ARN}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        continue-on-error: false

      - name: Terraform Init
        run: |
          terraform init -reconfigure

      - name: Terraform Validate
        run: terraform validate

      - name: Setup tflint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Run tflint
        run: |
          tflint --init
          tflint --recursive || true

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan \
            -var-file=envs/dev.tfvars \
        continue-on-error: true

      - name: Check plan status
        if: steps.plan.outcome == 'failure'
        run: exit 1
